import { PERMISSIONS, PermissionType } from "./permissions.js";
import { Role } from "./enums.js";

export const USER_ROLES = Role;
export type UserRoleType = Role;

export const ROLE_PERMISSIONS: Record<UserRoleType, PermissionType[]> = {
  SUPER_ADMIN: [
    PERMISSIONS.ADD_ADMIN,
    PERMISSIONS.MANAGE_PLATFORM,
  ],
  ADMIN: [
    PERMISSIONS.MANAGE_BILLING,
    PERMISSIONS.VIEW_ALL_PROJECTS,
    PERMISSIONS.MANAGE_ALL_USERS,
    PERMISSIONS.INVITE_USERS,
    PERMISSIONS.CREATE_PROJECT,
    PERMISSIONS.MANAGE_PROJECT,
    PERMISSIONS.APPROVE_MILESTONE,
    PERMISSIONS.VIEW_INVOICES,
    PERMISSIONS.MANAGE_DOCUMENTS,
  ],
  MANAGER: [
    PERMISSIONS.INVITE_USERS,
    PERMISSIONS.CREATE_PROJECT,
    PERMISSIONS.MANAGE_PROJECT,
    PERMISSIONS.APPROVE_MILESTONE,
    PERMISSIONS.VIEW_INVOICES,
    PERMISSIONS.MANAGE_DOCUMENTS,
  ],
  DEVELOPER: [
    PERMISSIONS.VIEW_ASSIGNED_PROJECTS,
    PERMISSIONS.UPDATE_TASKS,
    PERMISSIONS.UPLOAD_DOCUMENTS,
  ],
  CLIENT: [
    PERMISSIONS.VIEW_OWN_PROJECT,
    PERMISSIONS.APPROVE_DESIGN,
    PERMISSIONS.VIEW_OWN_INVOICES,
    PERMISSIONS.LEAVE_COMMENTS,
  ],
};

export const hasPermission = (
  role: UserRoleType,
  permission: PermissionType,
): boolean => (ROLE_PERMISSIONS[role] ?? []).includes(permission);